# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIGameDB-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUIGameDB-API
  pod 'IGDB-SWIFT-API', git: "https://github.com/husnjak/IGDB-API-SWIFT.git"
  
  target 'SwiftUIGameDB-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIGameDB-APIUITests' do
    # Pods for testing
  end

end
